# Generated by Django 5.2.1 on 2025-05-10 20:54

from django.db import migrations

def populate_team(apps, schema_editor):
    entries = {
        "team alpha": "The Alpha team",
        "team beta": "The Beta team",
        "team gamma": "The Gamma team"
    }
    Team = apps.get_model("accounts", "Team")
    for key, value in entries.items():
        team_objects= Team(name=key, description=value)
        team_objects.save()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_default_roles'),
    ]

    operations = [
        migrations.RunPython(populate_team),   # dont forget!
    ]
